# 仅仅作为dubbo接口的工程,不需要配置tomcat端口
#server:
#  port: 8087
server:
  port: 12111


## dubbo配置
spring:
  dubbo:
    application:
      name: springboot-dubbo-provider #应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo #暴露接口的协议
      port: 20880 #dubbo服务暴露的端口
    scan: com.zj.test.dobboprovider.service.impl #扫描的包名
    timeout: 3000
  datasource:
    url: jdbc:mysql://localhost

